rename_to_descriptive_col_names <- function() {

    # Return a list of meaningfull names
    
    tidyColNames <- c("MeanTimeDomainBodyAccelerationInX", 
                      "MeanTimeDomainBodyAccelerationInY",
    "MeanTimeDomainBodyAccelerationInZ", 
    "StandardDevTimeDomainBodyAccelerationInX",
    "StandardDevTimeDomainBodyAccelerationInY", 
    "StandardDevTimeDomainBodyAccelerationInZ",
    "MeanTimeDomainGravityAccelerationInX", 
    "MeanTimeDomainGravityAccelerationInY", 
    "MeanTimeDomainGravityAccelerationInZ", 
    "StandardDevTimeDomainGravityAccelerationInX",
    "StandardDevTimeDomainGravityAccelerationInY", 
    "StandardDevTimeDomainGravityAccelerationInZ",
    "MeanTimeDomainJerkOfTheBodyInX", 
    "MeanTimeDomainJerkOfTheBodyInY", 
    "MeanTimeDomainJerkOfTheBodyInZ", 
    "StandardDevTimeDomainJerkOfTheBodyInX",
    "StandardDevTimeDomainJerkOfTheBodyInY", 
    "StandardDevTimeDomainJerkOfTheBodyInZ",
    "MeanTimeDomainBodyGyroInX", "MeanTimeDomainBodyGyroInY", 
    "MeanTimeDomainBodyGyroInZ", "StandardDevTimeDomainBodyGyroInX", 
    "StandardDevTimeDomainBodyGyroInY", "StandardDevTimeDomainBodyGyroInZ", 
    "MeanTimeDomainJerkOfTheBodyGyroInX", "MeanTimeDomainJerkOfTheBodyGyroInY",
    "MeanTimeDomainJerkOfTheBodyGyroInZ", 
    "StandardDevTimeDomainJerkOfTheBodyGyroInX",
    "StandardDevTimeDomainJerkOfTheBodyGyroInY", 
    "StandardDevTimeDomainJerkOfTheBodyGyroInZ",
    "MeanTimeDomainBodyAccelerationMagnitudeInX", 
    "StandrdDevTimeDomainBodyAccelerationMagnitudeInX",
    "MeanTimeDomainGravityAccelerationMagnitude", 
    "StandardDevTimeDomainGravityAccelerationMagnitude",
    "MeanTimeDomainJerkOfTheBodyMagnitude", 
    "StandardDevTimeDomainJerkOfTheBodyMagnitude", 
    "MeanTimeDomainBodyGyroscopeMagnitude", 
    "StandardDevTimeDomainBodyGyroscopeMagnitude", 
    "MeanTimeDomainJerkOfTheBodyGyroscopeMagnitude", 
    "StandardDevTimeDomainJerkOfTheBodyGyroscopeMagnitude",
    "MeanFrequencyDomainBodyAccelerationInX", 
    "MeanFrequencyDomainBodyAccelerationInY", 
    "MeanFrequencyDomainBodyAccelerationInZ", 
    "StandardDevFrequencyDomainBodyAccelerationInX",
    "StandardDevFrequencyDomainBodyAccelerationInY", 
    "StandardDevFrequencyDomainBodyAccelerationInZ",
    "MeanFrequencyDomainJerkOfTheBodyInX", 
    "MeanFrequencyDomainJerkOfTheBodyInY", 
    "MeanFrequencyDomainJerkOfTheBodyInZ", 
    "StandardDevFrequencyDomainJerkOfTheBodyInX",
    "StandardDevFrequencyDomainJerkOfTheBodyInY", 
    "StandardDevFrequencyDomainJerkOfTheBodyInZ", 
    "MeanFrequencyDomainBodyGyroscopeInX", 
    "MeanFrequencyDomainBodyGyroscopeInY", 
    "MeanFrequencyDomainBodyGyroscopeInZ", 
    "StandardDevFrequencyDomainBodyGyroscopeInX", 
    "StandardDevFrequencyDomainBodyGyroscopeInY", 
    "StandardDevFrequencyDomainBodyGyroscopeInZ",
    "MeanFrequencyDomainBodyAccelerationMagnitude", 
    "StandardDevFrequencyDomainBodyAccelerationMagnitude", 
    "MeanFrequencyDomainJerkOfTheBodyMagnitude", 
    "StandardDevFrequencyDomainJerkOfTheBodyMagnitude", 
    "MeanFrequencyDomainBodyGyroscopeMagnitude", 
    "StandardDevFrequencyDomainBodyGyroscopeMagnitude", 
    "MeanFrequencyDomainJerkOfTheBodyGyroscopeMagnitude", 
    "StandardDevFrequencyDomainJerkOfTheBodyGyroscopeMagnitude", 
    "subjects", "activities")
    
    return(tidyColNames)
}